# Generated by Django 3.2 on 2022-02-24 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('name', models.TextField(default=None, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Название рецепта')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(default=None, max_length=50, verbose_name='Ингредиенты')),
                ('recipes', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='book_recipes.recipes', verbose_name='Название рецепта')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'unique_together': {('recipes', 'ingredient')},
            },
        ),
    ]
